### ISSUE TITLE
Misc. Improvements

### ISSUE THREAD

**Issue by DGKSK8LIFE** [awtybots/FRC-2020#8]

**Comment by AlexDvorak** [comment]
Could you elaborate on what the exact issue is?

**Comment by DGKSK8LIFE** [comment]
> Could you elaborate on what the exact issue is?

There is no exact issue per se, but I see room for improvement in how you are using Java's encapsulation in code. Today I'm gonna fork said code and open a PR with fixes/"optimizations" in your encapsulation techniques/uses.

**Comment by DGKSK8LIFE** [comment]
Encapsulation used is actually necessary/proper. Good job team!
